### ISSUE TITLE
Make separation char configurable

### ISSUE THREAD

**Issue by schmittlauch** [cloutierjo/titleUrl#5]
Hi,
I migrated from [Add URL to titlebar](https://github.com/erichgoldman/add-url-to-window-title/ ) add-on which uses a `-` as the default separator between title and URL, but this can be configured.

Now all my keepassx autotype configurations include the `-` separator. Can you consider making the separator char configurable or do I have to change all my configurations?

**Comment by cloutierjo** [comment]
Hello,
I could add this configuration, but at the moment I’m busy replacing another addons before the Firefox 57 deadline. If someone wants to contribute the change I’ll be happy to test it and do a release, in other case it might go after the Firefox 57 release.

Still as a workaround, I don’t know if it’s possible with keepassx, but with keepass 2.x you can check the option to match an entry if the URL is contained in the windows title. That work well with any separator as long as the URL field is filled properly.

In the meantime, sorry for the inconvenience, I’ll update this issue when I can make the change.

**Comment by cloutierjo** [comment]
Thanks to Azlond, this feature is now added, you can try it using the beta channel available on https://addons.mozilla.org/fr/firefox/addon/url-in-title/ 

If everything is good, I'll do the release next week.

**Comment by alerque** [comment]
Thanks @Azlond this feature was a blocker for me and I just moved over. At least at first pass it seems to work (FF56).

**Comment by schmittlauch** [comment]
Coming back to my original problem of not wanting to change the AutoType rules in my KeepassX I just found out, that this add-on puts `protocol://host.na.me/` into the titlebar, while my formerly used addon only puts `host.na.me/` (without the protocol).

But I'm not sure whether that's worth a setting. You usually want to always use https for sites requiring a login.

**Comment by cloutierjo** [comment]
There is a lot of format used in former add-ons: 
* full URL : https://host.na.me:8080/path/to/everything.html
* simple domain : host.na.me
* simple domain with safe guard : host.na.me/
* completely configurable title: ~_~page title~_~host.na.me||path/to/everything.html\/\/8080 (well I hope no one did a config like this but some add-ons give that possibility)

So I figured that giving the most info by default would take care at least for the first 3 cases and most of the 4th case. Obviously if the autotype setting include more than the URL information that increase a lot the possibilities.

On the longer term goal I have is to provide a complete title customization similar to some former add-ons, but this isn't planned in the short term for me.

In the meantime, I would still go with another setting because as much as your autotype setting doesn't include the protocol, as much other people setting does include it.

**Comment by TheZ3ro** [comment]
@schmittlauch @cloutierjo I've tried to address the protocol thing in #8

**Comment by cloutierjo** [comment]
Thanks to TheZ3ro the protocol is now optional. I've released a beta version that is available using the beta channel available on https://addons.mozilla.org/fr/firefox/addon/url-in-title/

**Comment by cloutierjo** [comment]
Fixed in version 0.4 and submitted to AMO.
